name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ anusuyakal }}  # Ensure you set DOCKER_USERNAME in GitHub secrets
          password: ${{ Swift@9019 }}  # Ensure you set DOCKER_PASSWORD in GitHub secrets

      - name: Build Docker Image
        run: docker build . -t anusuya.kaliaperumal/mypython:${{ github.sha }}

      - name: Run Tests
        run: |
          docker run --rm anusuya.kaliaperumal/mypython:${{ github.sha }} python -m unittest discover -s tests

      - name: Push Docker Image
        run: docker push anusuya.kaliaperumal/mypython:${{ github.sha }}

      - name: Deploy
        run: |
          ssh user@yourserver 'docker pull anusuya.kaliaperumal/mypython:${{ github.sha }} && docker run -d anusuya.kaliaperumal/mypython:${{ github.sha }}'
