name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build . -t yourusername/yourapp:${{ github.sha }}

      - name: Run Tests
        run: |
          docker run yourusername/yourapp:${{ github.sha }} python -m unittest discover tests

      - name: Push Docker Image
        run: docker push yourusername/yourapp:${{ github.sha }}

      - name: Deploy
        run: |
          ssh user@yourserver 'docker pull yourusername/yourapp:${{ github.sha }} && docker run -d yourusername/yourapp:${{ github.sha }}'
